### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by jonasfoyth** [Idein/dockworker#114]
Hello! I'm testing the lib in some projects and i need to update a continers enviroments variables.

The first idea was remove and create a new container with a new enviroment, but isn't a good idea remove and create all the time. 

The second ideia was use exec_container function with env option. However, the struct CreateExecOptions is pub but env option is private. 

Any ideia to make this enviroment update? Thx.

**Comment by eldesh** [comment]
Thanks for the suggestion.
The `env` in `CreateExecOptions` looks like it should be public.

**Comment by eldesh** [comment]
This feature is enabled in #115.
You can use this feature as follows
`dockworker = { git = "https://github.com/Idein/dockworker.git", rev = "ffd1d2a" }`
