### ISSUE TITLE
Perform unit tests sequentially

### ISSUE THREAD

**Issue by eldesh** [Idein/dockworker#70]
Unit test cases conflicts each other if it uses a docker image same to other case.
ref. #69

```
#[cfg(test)]
fn test () {
    let image = ...;
    test_api_0(&image);
    test_api_1(&image);
    test_api_2(&image);
    ...
}
```

**Comment by acidghost** [comment]
@eldesh Please, read this https://doc.rust-lang.org/book/ch11-02-running-tests.html#running-tests-in-parallel-or-consecutively

**Comment by eldesh** [comment]
https://doc.rust-lang.org/book/ch11-02-running-tests.html#running-tests-in-parallel-or-consecutively sais:

```
If you don’t want to run the tests in parallel ...
Take a look at the following example:
$ cargo test -- --test-threads=1
```

We want to run unit tests in parallel, because Docker API calls need to work well in parallel.
